### ISSUE TITLE
Add support for EpiServer 12

### ISSUE THREAD

**Issue by tomaszmadeyski** [fortedigital/EpiResponsivePicture#18]
Currently, this code targets EpiServer v11 (.net Framework version). Due to this fact it is impossible to use it (via nuget package) in solutions that are using EpiServer v12 (.net core version)

Desired outcome: code compatible with EpiServer v12

Note: in our research it turns out that it might be hard to have a code/nuget that supports both EpiServer v12 and v11. Packages like [Geta404](https://github.com/Geta/404handler) created completely [new nuget ](https://github.com/Geta/geta-notfoundhandler)to target .net 5. Maybe a way to go is to create new branch and publish nuget with new major version targetting .net 5 and keep maintaining Epi v11 in current major version of nuget. (ie v 1.* targets Epi v11, v 2.* targets Epi v12)

**Comment by Deepa-Puranik** [comment]
New nuget package will be created for Epi V12 support? Is it available now?

**Comment by tomaszmadeyski** [comment]
We'll create a new version of existing nuget that will target .net6 so it can be used with EpiServer v12. It's not ready yet but we're wrapping up on development so it should be available soon

**Comment by tomaszmadeyski** [comment]
There's a version 1.x available that is targetting Epi v12. Closing
