### ISSUE TITLE
CMS 12 Edit view content tree not loading

### ISSUE THREAD

**Issue by Deepa-Puranik** [fortedigital/EpiResponsivePicture#41]
Hello,

If we use the Forte.EPiResponsivePicture with latest CMS version of 12.17.0 in our project(.net 6.0), content tree of first website will not load. If we remove this package it works. 
Can you please help in understanding why content tree is not loading if we add this package.
![image](https://user-images.githubusercontent.com/75352823/220839248-cfcefcc4-a223-4cdd-b0f2-de746885769b.png)

**Comment by tomaszmadeyski** [comment]
Can you check your console log for any errors? Also, in network tab are there any errors (404,500 etc)?

**Comment by Deepa-Puranik** [comment]
No errors in Network tab.  In console there are these errors related to visitor group and thumbnail.
![image](https://user-images.githubusercontent.com/75352823/220848365-333219e8-0a93-4fbc-b772-c30d2c765936.png)

**Comment by piotr-szczygiel** [comment]
Hi @Deepa-Puranik! I just installed brand new Alloy template and verified all versions from 12.13.2 up to 12.17.0. Seems to work in all cases. 
Regarding your issue: 
- are you installing new CMS project or upgrading from CMS 11 to CMS12?
- Could you share your configuration of `AddForteEpiResponsivePicture`?
- Do you use latest version (1.0.20) of EpiResponsivePicture?

**Comment by Deepa-Puranik** [comment]
Hello,

Yeah it works all fine in ALloy template website just checked adding it there. 
And related to our project:
- We upgraded our project from 11.20 to 12.17.0
- Yes. Here is Startup code:
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews(ConfigureMvcOptions)
                // Newtonsoft.Json is added for compatibility reasons
                // The recommended approach is to use System.Text.Json for serialization
                // Visit the following link for more guidance about moving away from Newtonsoft.Json to System.Text.Json
                // https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to
                .AddNewtonsoftJson(options =>
                {
                    options.UseMemberCasing();
                });
            if (_webHostingEnvironment.IsDevelopment())
            {
                // AppDomain.CurrentDomain.SetData("DataDirectory", Path.Combine(_webHostingEnvironment.ContentRootPath, "App_Data"));
                services.Configure<SchedulerOptions>(options => options.Enabled = false);
                services.Configure<DataAccessOptions>(o =>
                {
                    o.ConnectionStrings.Add(new ConnectionStringOptions
                    {
                        ConnectionString = Configuration.GetConnectionString("EPiServerDB"),
                        Name = "EPiServerDB"
                    });
                });
                services.AddControllersWithViews().AddRazorRuntimeCompilation();
            }
            services.AddABTesting(Configuration.GetConnectionString("EPiServerDB"));
            services
               .AddCmsAspNetIdentity<ApplicationUser>()
               .AddCms()
               .AddAdvanced()
               .AddAdminUserRegistration()
               .AddEmbeddedLocalization<Startup>();

            // Required by Wangkanai.Detection
            services.AddDetection();
            services.AddFind();
            //services.AddBaaijteOptimizelyImageSharp();
            services.AddHttpContextAccessor();
            services.AddMemoryCache();
            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromSeconds(10);
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
            });
            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
            services.AddSingleton(x =>
            {
                var actionContext = x.GetRequiredService<IActionContextAccessor>().ActionContext;
                var factory = x.GetRequiredService<IUrlHelperFactory>();
                return factory.GetUrlHelper(actionContext);
            });
            var connectionString = this.Configuration.GetConnectionString("EPiServerDB");// Retrieve connection string here
            services.AddNotFoundHandler(o =>
            {
                o.UseSqlServer(connectionString);
                o.BufferSize = 30;
                o.ThreshHold = 5;
                o.HandlerMode = FileNotFoundMode.On;
                o.IgnoredResourceExtensions = new[] { "jpg", "gif", "png", "css", "js", "ico", "swf", "woff" };
                o.Logging = LoggerMode.On;
                o.LogWithHostname = false;
                //o.AddProvider<NullNotFoundHandlerProvider>();
            });
            services.AddOptimizelyNotFoundHandler(o =>
            {
                o.AutomaticRedirectsEnabled = true;
            });
            services.AddOutputCaching();
            services.AddSitemaps(x =>
            {
                x.EnableLanguageDropDownInAdmin = false;
                x.EnableRealtimeCaching = true;
                x.EnableRealtimeSitemap = false;
            });
            services.Configure<UIOptions>(options =>
            {
                options.WebSocketEnabled = false;
            });
            services.AddForteEpiResponsivePicture();
            services.AddScoped<ContentLocator>();
            services.AddScoped<SitemapHelper.SitemapGenerator>();
            services.AddGetaCategories();
            services.AddRazorPages();
            services.AddRobotsHandler();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IContentEvents contentEvents, IHttpContextAccessor accessor)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();
            app.UseStaticFiles(new StaticFileOptions()
            {
                FileProvider = new PhysicalFileProvider(
                Path.Combine(Directory.GetCurrentDirectory(), @"Static")),
                RequestPath = new PathString("/Static")
            });
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapContent();
                endpoints.MapRazorPages();
            });
            //app.UseBaaijteOptimizelyImageSharp();
            UrlHelpers.SetHttpContextAccessor(accessor);
            // setup app's root folders
            AppDomain.CurrentDomain.SetData("ContentRootPath", env.ContentRootPath);
            AppDomain.CurrentDomain.SetData("WebRootPath", env.WebRootPath);
            app.UseGetaCategories();
            app.UseStatusCodePagesWithReExecute("/error/{0}");
            app.UseNotFoundHandler();
            app.UseOutputCaching();
            contentEvents.PublishedContent += OnPublishedContent;
            //app.UseMiddleware<RobotsHandler>();
            app.UseForteEpiResponsivePicture();
        }
- Yes we have latest stable version 1.0.20 of EpiResponsivePicture

-

**Comment by piotr-szczygiel** [comment]
@Deepa-Puranik from your setup I see correct configuration of EpiResponsivePicture. Apparently something else has influence on our nuget, so issues appears in CMS. Could you please try to reporduce the issue on Alloy and then let us know about what steps that needs to be done? We'll be happy to fix the problem then.

**Comment by Deepa-Puranik** [comment]
@piotr-szczygiel  Content tree is started working all again now, but I am not able to use Image file inherited from ImageBase type when we add images it will be of existing ImageFile block type which already there not the new one created using Forte package.

**Comment by Deepa-Puranik** [comment]
This issue can be closed as everything is working now as expected.
