### ISSUE TITLE
Inconsistent decimal separator for FocalPointQuery in ImageSharpResizedUrlGenerator

### ISSUE THREAD

**Issue by kostadinM29** [fortedigital/EpiResponsivePicture#50]
In the **FocalPointQuery** method defined in **ImageSharpResizedUrlGenerator.cs** file the separator is language dependent. For example with **it** Culture the separator is a comma and with **en** it is a dot.

 I suggest formatting the two focal point decimal values with **CultureInfo.InvaruantCulture**. That's how I fixed it in my multi-language Optimizely project.

**Comment by tomaszmadeyski** [comment]
Hi

Thank you for your ticket. Can you please give us some more info about what the result of this inconsistency is so that we're sure we fix your error properly?

**Comment by kostadinM29** [comment]
Hello, thanks for the fast reply!

Here is how to reproduce it:
```c#
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
var englishCultureQuery = $"{focalPoint.X:0.###},{focalPoint.Y:0.###}"; // Outputs x.xxx,x.xxx

Thread.CurrentThread.CurrentCulture = new CultureInfo("es-UY");
var spanishCultureQuery = $"{focalPoint.X:0.###},{focalPoint.Y:0.###}"; // Outputs x,xxx,x,xxx

Thread.CurrentThread.CurrentCulture = new CultureInfo("it");
var italianCultureQuery = $"{focalPoint.X:0.###},{focalPoint.Y:0.###}"; // Outputs x,xxx,x,xxx

var invariantCultureQuery = $"{focalPoint.X.ToString("0.###", CultureInfo.InvariantCulture)},{focalPoint.Y.ToString("0.###", CultureInfo.InvariantCulture)}"; // Outputs x.xxx,x.xxx consistently
```
