### ISSUE TITLE
Override queries in ResizedUrlGeneratorBase

### ISSUE THREAD

**Issue by dawid-grajewski-fortedigital** [fortedigital/EpiResponsivePicture#56]
Hi,

Sometimes for reasons beyond our control we get image's base url with some query strings already in it, eg.
 ```
https://localhost:5000/globalassets/picture.jpg?width=1200&height=640
```
When put through url generation eg. 
```
return ServiceLocator.Current
    .GetInstance<IResizedUrlGenerator>()
    .GenerateUrl(baseUrl, GetImageWidth(model), source, profile, focalPoint)
    .ToString();
```
All the query parameters are added, no matter if they are already present or not, so we may end up with url like eg (with double 'width' and 'height'). 
```
https://localhost:5000/globalassets/picture.jpg?width=1200&width=1200&height=640&height=640&quality=60&rxy=0,0&rmode=Crop
```
In such case query parameters are being concatenated. That results in picture resize request of size 12001200x640640. Which is way too big and ends with server error.

For now we resolved our issue with just clearing the whole query string of picture's base url before generating resized url, like.
```
baseUrl = new UrlBuilder(baseUrl)
{
    Query = ""
}
.ToString();
```

My main question is if this is a desired behaviour or maybe it should be changed to instead override the query parameter if it already exists? 

I can see that class `ResizedUrlGeneratorBase` uses:
```
builder.Add(/*some value*/);
``` 
How about changing it to :
```
builder.AddOrOverride(/*some value*/);
```
Which could be implemented something like:
```
public static UrlBuilder AddOrOverride(this UrlBuilder target, string key, string value) => target.Remove(key).Add(key, value);
```

Would love to hear your opinion on that. If you want me to provide any more insights into our case, don't hesitate to contact me directly.

**Comment by tomaszmadeyski** [comment]
I don't think the behavior you described is desired/designed. I agree that overriding the value is much better. We'll try to fix it in spare time, or feel free to add PR :)
